name: Update README

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Update README
      run: |
        echo "This is a real-time chat application built using **React** for the frontend and **Node.js** for the backend." > README.md
        echo "Last updated: $(date)" >> README.md
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "johnwakaba146@gmail.com"
        git config --global user.name "SK108045"
        git add README.md
        git commit -m "Update README $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
